# Generated by Django 6.0.7 on 2026-07-08 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={"ordering": ["-created_at"]},
        ),
    ]
