# Generated by Django 6.0.6 on 2026-07-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('releaseYear', models.IntegerField()),
                ('genre', models.CharField(choices=[('', '--- 장르선택 ---'), ('ACTION', '액션'), ('ROMANCE', '로맨스'), ('COMEDY', '코미디'), ('THRILLER', '스릴러'), ('SF', 'SF'), ('DRAMA', '드라마')], default='', max_length=20)),
                ('rating', models.FloatField()),
                ('runningTime', models.IntegerField()),
                ('content', models.CharField(max_length=500)),
                ('director', models.CharField(max_length=20)),
                ('mainActor', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
